package com.parqour.bot.Enums;

public enum State {
    START,
    ADMIN,
    PARKING,
    WAITING_PARKING,
    WAITING_CRITICALITY,
    WAITING_PROBLEM_AREA,
    WAITING_DESCRIPTION,
    CONTACT,

    WAITING_ADD_USER,
    WAITING_ADD_USER_ROLE,

    SEARCHING,
    WAITING_SEARCHING,
    CANCELLED,

    ADMIN_WAITING_PARKING,
    ADMIN_WAITING_OPERATOR,
    ADMIN_OPERATORS_PARKING,
    ADMIN_WAITING_OPERATORS_PARKING,
    ADMIN_WAITING_DUTY_OPERATOR, ADMIN_WAITING_DUTY_DATE,
    ADMIN_WAITING_OPERATORS_MANAGING,
    ADMIN_WAITING_MANAGE_PARKING, ADMIN_WAITING_MANAGE_PARKING_OPERATOR,
    ADMIN_WAITING_PARKINGS_MANAGING,
    ADMIN_WAITING_SET_ADMIN, ADMIN_WAITING_SET_USER,
    ADMIN_WAITING_GROUP_NAME
}
